apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-03T06:13:51Z"
  generation: 2
  labels:
    app: wordpress
  name: wordpress
  namespace: default
  resourceVersion: "23610"
  selfLink: /apis/apps/v1/namespaces/default/deployments/wordpress
  uid: ba33868c-461c-4d0b-a46f-8b77e5d80bf3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: wordpress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_HOST
              name: wp-secret
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_USER
              name: wp-secret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_PASSWORD
              name: wp-secret
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              key: WORDPRESS_DB_NAME
              name: wp-secret
        image: wordpress:latest
        imagePullPolicy: Always
        name: wordpress-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30